### ISSUE TITLE
intersection-points for certain values causes infinite loop

### ISSUE THREAD

**Issue by zkry** [soegaard/metapict#30] opened 2019-08-16 19:19 UTC
Hello, I first want to thank you for the work you do on this wonderful library! 

I was encountering a problem with the intersection-points function. For example, when running the query `(intersection-points (curve (pt 1 -1) .. (pt 2 -1) .. (pt 1 -1))  (curve (pt 1 -1) .. (pt 1 -1)))`, an infinite loop occurs and the function never returns. It looks like when the intersection point at the end of a curve such situation occurs. The example `(intersection-points (curve (pt 1 -1) .. (pt 1 -1))  (curve (pt 1 -1) .. (pt 1 -1)))` also causes an infinite loop.

It seems like when intersection-points calculates the next point, its next step is the same as the initial value.

**Comment by soegaard** [comment] 2019-08-17 14:21
Hi,

I can confirm there is a bug. 

At first I thought the reason was that  the second curve (curve P .. P) was a point,
but as you point out, if the endpoint of curve meets the other,  there is a problem.

I'll investigate further.

/Jens Axel

**Comment by soegaard** [comment] 2019-08-17 19:46
Hi again,

I have committed a fix. Thanks for your observation that the problem
was related to the end point.

Note that if the curves are closed (same start and end point)
and the intersection point is a start/end point, intersection-points
now returns the same point twice.

**Comment by zkry** [comment] 2019-08-18 12:17
Great! Thanks for the quick reply.

**Closed** 2019-08-20 19:32 UTC
